package com.ngocphuoc.crime_report.enums;

public enum AuditAction {
    CASE_CREATED,
    CASE_ASSIGNED,
    CASE_ACCEPTED,
    CASE_LOCKED,
    CASE_UNLOCKED,
    CASE_STATUS_CHANGED,
    REPORTER_IDENTITY_ENCRYPTED,
    REPORTER_IDENTITY_DECRYPTED,
    URGENCY_SCORE_CALCULATED,
    AI_SPAM_ANALYZED,
    CASE_MARKED_SPAM_OR_FAKE,
    CASE_MARKED_NEEDS_REVIEW
}
