spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:crime_report_dispatch}
    username: ${DB_USERNAME:crime_user}
    password: ${DB_PASSWORD:crime_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

app:
  jwt:
    secret: ${JWT_SECRET:crime-report-dispatch-secret-key-must-be-at-least-32-bytes}
    # 24h
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}