spring:
  application:
    name: urgency-service
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:crime_urgency}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME:crime_user}
    password: ${DB_PASSWORD:crime_password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8084}
